# Generated by Django 6.0.4 on 2026-05-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sangam', '0002_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='increment_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='max_members',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='group',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='late_fine',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='meeting_day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Sunday', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='weekly_amount',
            field=models.FloatField(default=0),
        ),
    ]
