# Generated by Django 6.0.4 on 2026-06-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sangam', '0003_group_description_group_increment_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
